image: adoptopenjdk/openjdk8-openj9:alpine-slim

variables:
  MAVEN_CLI_OPTS: "--show-version --batch-mode \
    -Dmaven.repo.local=.m2/repository \
    -Duser.timezone=Asia/Jakarta \
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

cache:
  paths:
    - .m2/repository/

default:
  before_script:
    - apk add --update --no-cache git
    - git --version
    - git remote set-url --push origin "https://${GITLAB_USER_LOGIN}:${READ_WRITE_REPOSITORY_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
    - git config user.name "${GITLAB_USER_NAME}"
    - git config user.email "${GITLAB_USER_EMAIL}"

stages:
  - build
  - test
  - release

build:
  stage: build
  script: ./mvnw $MAVEN_CLI_OPTS test-compile
  allow_failure: false
  only:
    - develop

test:
  variables:
    JACOCO_REPORT_HTML: $CI_PROJECT_DIR/target/site/jacoco/index.html
  stage: test
  script:
    - ./mvnw $MAVEN_CLI_OPTS verify
    - if [ -f $JACOCO_REPORT_HTML ]; then cat $JACOCO_REPORT_HTML | grep -o "Total[^%]*%"; fi
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  only:
    - develop

release:
  stage: release
  dependencies:
    - test
  script:
    - ./mvnw $MAVEN_CLI_OPTS gitflow:release
  only:
    - develop
  when: manual
